version: '3.8'
services:
  rocm:
    container_name: rocm
    build:
      context: ./
      dockerfile: Dockerfile.rocm
      args:
        group-add: video 
    volumes:
      - ./:/home/app
    devices:
      - /dev/kfd
      - /dev/dri/card0
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
